export const OPTIONS = [
  {
    id: "A1",
    name: "Audi A1",
    position: 1,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=1",
    description:
      "La gamme Audi A1 est composée de 2 modèles citadins parfaitement adaptés à un usage en ville.",
    backgrounds: {
      model_id: "A1_sportback",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a1.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a1.webp",
    },
    volume: 7310,
    boost: 1.0,
    tag: ["Citadine"],
    models: [
      {
        id: "A1_sportback",
        name: "A1 Sportback",
        position: 1,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 7706,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: 1001,
        aliases: ["carline.a1sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a1/a1-sportback/finitions.html",
        description: "La citadine dynamique et connectée",
        images: {
          mobile: "A1/modeles/A1_Sportback_D.png",
          desktop: "A1/modeles/A1_Sportback_D.png",
        },
      },
      {
        id: "A1_allstreet",
        name: "A1 allstreet",
        position: 2,
        tracking: {
          derivat_name: "allstreet",
        },
        volume: 951,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: -1,
        aliases: ["carline.a1cc"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a1/a1-allstreet/finitions.html",
        description: "La citadine baroudeuse surélévée",
        images: {
          mobile: "A1/modeles/A1_allstreet_D.png",
          desktop: "A1/modeles/A1_allstreet_D.png",
        },
      },
    ],
  },
  {
    id: "Q2",
    name: "Audi Q2",
    position: 2,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=15",
    description:
      "La gamme Q2 est composée de 2 modèles de SUV Compacts parfaitement adaptés à la ville et personnalisables.",
    backgrounds: {
      model_id: "Q2",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q2.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q2.webp",
    },
    volume: 5410,
    boost: 1.0,
    tag: ["SUV", "Urbain"],
    models: [
      {
        id: "Q2",
        name: "Q2",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 5878,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 687,
        aliases: ["carline.q2"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q2/q2/finitions.html",
        description: "Le SUV Compact urbain",
        images: {
          mobile: "Q2/modeles/Q2_D.png",
          desktop: "Q2/modeles/Q2_D.png",
        },
      },
      {
        id: "SQ2",
        name: "SQ2",
        position: 2,
        tracking: {
          derivat_name: "S",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.sq2"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q2/sq2/finitions.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "Q2/modeles/SQ2_D.png",
          desktop: "Q2/modeles/SQ2_D.png",
        },
      },
    ],
  },
  {
    id: "A3",
    name: "Audi A3",
    position: 3,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=3",
    description:
      "La gamme Audi A3 est composée de 7 modèles conçus pour un usage polyvalent dédié à la vie de tous les jours.",
    backgrounds: {
      model_id: "A3_sportback",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a3.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a3.webp",
    },
    volume: 8442,
    boost: 1.0,
    tag: ["Compacte", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "A3_sportback",
        name: "A3 Sportback",
        position: 1,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 6107,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: 726,
        aliases: ["carline.a3sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/a3-sportback/finitions.html",
        description: "La compacte iconique et connectée",
        images: {
          mobile: "A3/modeles/A3_Sportback_D.png",
          desktop: "A3/modeles/A3_Sportback_D.png",
        },
      },
      {
        id: "A3_sportback_tfsi_e",
        name: "A3 Sportback TFSI e",
        position: 2,
        tracking: {
          derivat_name: "Sportback TFSI e",
        },
        volume: 1643,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: 545,
        aliases: ["carline.a3sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/a3-sportback-tfsi-e/finitions.html",
        description: "La compacte hybride rechargeable",
        images: {
          mobile: "A3/modeles/A3_Sportback_TFSIe_D.png",
          desktop: "A3/modeles/A3_Sportback_TFSIe_D.png",
        },
      },
      {
        id: "A3_allstreet",
        name: "A3 allstreet",
        position: 3,
        tracking: {
          derivat_name: "allstreet",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "12/03/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/a3-allstreet/finitions.html",
        description: "La citadine baroudeuse surélévée",
        images: {
          mobile: "A3/modeles/A3_Sportback_TFSIe_D.png",
          desktop: "A3/modeles/A3_Sportback_TFSIe_D.png",
        },
      },
      {
        id: "A3_berline",
        name: "A3 Berline",
        position: 4,
        tracking: {
          derivat_name: "Berline",
        },
        volume: 638,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: 133,
        aliases: ["carline.a3limo"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/a3-berline/finitions.html",
        description: "La compacte en version berline",
        images: {
          mobile: "A3/modeles/A3_Berline_D.png",
          desktop: "A3/modeles/A3_Berline_D.png",
        },
      },
      {
        id: "S3_sportback",
        name: "S3 Sportback",
        position: 5,
        tracking: {
          derivat_name: "S3 Sportback",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: -1,
        aliases: ["carline.s3sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/s3-sportback/moteurs.html",
        description: "La version S compacte, plus dynamique",
        images: {
          mobile: "A3/modeles/S3_Sportback_D.png",
          desktop: "A3/modeles/S3_Sportback_D.png",
        },
      },
      {
        id: "S3_berline",
        name: "S3 Berline",
        position: 6,
        tracking: {
          derivat_name: "S3 Berline",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["carline.s3sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/s3-berline/moteurs.html",
        description: "La version S berline, plus dynamique",
        images: {
          mobile: "A3/modeles/S3_Berline_D.png",
          desktop: "A3/modeles/S3_Berline_D.png",
        },
      },
      {
        id: "RS_3_sportback",
        name: "RS 3 Sportback",
        position: 7,
        tracking: {
          derivat_name: "RS 3 Sportback",
        },
        volume: 218,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Citadine", 
        stock_level: -1,
        aliases: ["carline.rs3sb"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/nouvelle-rs-3-sportback.html",
        description: "La version RS compacte, façonnée par Audi Sport",
        images: {
          mobile: "A3/modeles/RS_3_Sportback_D.png",
          desktop: "A3/modeles/RS_3_Sportback_D.png",
        },
      },
      {
        id: "RS_3_berline",
        name: "RS 3 Berline",
        position: 8,
        tracking: {
          derivat_name: "RS 3 Berline",
        },
        volume: 50,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["carline.rs3limo"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a3/nouvelle-rs-3-berline.html",
        description: "La version RS berline, façonnée par Audi Sport",
        images: {
          mobile: "A3/modeles/RS_3_Berline_D.png",
          desktop: "A3/modeles/RS_3_Berline_D.png",
        },
      },
    ],
  },
  {
    id: "Q3",
    name: "Audi Q3",
    position: 4,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=9",
    description:
      "La gamme Q3 est composée de 6 modèles de SUV Compacts et polyvalents.",
    backgrounds: {
      model_id: "Q3_tfsi_e",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q3.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q3.webp",
    },
    volume: 4335,
    boost: 1.0,
    tag: ["SUV Compact", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "Q3",
        name: "Q3",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 2909,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 553,
        aliases: ["Q3 SUV", "carline.q3"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/q3/finitions.html",
        description: "Le SUV Compact polyvalent",
        images: {
          mobile: "Q3/modeles/Q3_D.png",
          desktop: "Q3/modeles/Q3_D.png",
        },
      },
      {
        id: "Q3_tfsi_e",
        name: "Q3 TFSI e",
        position: 2,
        tracking: {
          derivat_name: "TFSI e",
        },
        volume: 1591,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 228,
        aliases: ["carline.q3etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/q3-tfsi-e/finitions.html",
        description: "La version compacte hybride rechargeable",
        images: {
          mobile: "Q3/modeles/Q3_TFSI_e_D.png",
          desktop: "Q3/modeles/Q3_TFSI_e_D.png",
        },
      },
      {
        id: "Q3_sportback",
        name: "Q3 Sportback",
        position: 3,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 3124,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 600,
        aliases: ["carline.q3sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/q3-sportback/finitions.html",
        description: "Le SUV Coupé compact",
        images: {
          mobile: "Q3/modeles/Q3_Sportback_D.png",
          desktop: "Q3/modeles/Q3_Sportback_D.png",
        },
      },
      {
        id: "Q3_sportback_tfsi_e",
        name: "Q3 Sportback TFSI e",
        position: 4,
        tracking: {
          derivat_name: "Sportback TFSI e",
        },
        volume: 2468,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 544,
        aliases: ["carline.q3sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/q3-sportback-tfsi-e/finitions.html",
        description: "La version coupée compacte hybride rechargeable",
        images: {
          mobile: "Q3/modeles/Q3_Sportback_TFSI_e_D.png",
          desktop: "Q3/modeles/Q3_Sportback_TFSI_e_D.png",
        },
      },
      {
        id: "RS_Q3",
        name: "RS Q3",
        position: 5,
        tracking: {
          derivat_name: "RS",
        },
        volume: 10,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["RS Q3 SUV", "carline.rsq3"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/rs-q3.html",
        description: "La version compacte RS, façonnée par Audi Sport",
        images: {
          mobile: "Q3/modeles/RS_Q3_D.png",
          desktop: "Q3/modeles/RS_Q3_D.png",
        },
      },
      {
        id: "RS_Q3_sportback",
        name: "RS Q3 Sportback",
        position: 6,
        tracking: {
          derivat_name: "RS Sportback",
        },
        volume: 38,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.rsq3sb"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q3/rs-q3-sportback.html",
        description: "La version coupée RS, façonnée par Audi Sport",
        images: {
          mobile: "Q3/modeles/RS_Q3_Sportback_D.png",
          desktop: "Q3/modeles/RS_Q3_Sportback_D.png",
        },
      },
    ],
  },
  {
    id: "A4",
    name: "Audi A4",
    position: 5,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=4",
    description:
      "La gamme Audi A4 est composée de 6 modèles de routières polyvalentes et confortables.",
    backgrounds: {
      model_id: "A4_avant",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a4.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a4.webp",
    },
    volume: 2668,
    boost: 1.0,
    tag: ["Berline", "Break", "Sportive"],
    models: [
      {
        id: "A4_berline",
        name: "A4 Berline",
        position: 1,
        tracking: {
          derivat_name: "Berline",
        },
        volume: 314,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 75,
        aliases: ["carline.a4limo"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/a4-berline/finitions.html",
        description: "La berline iconique Audi",
        images: {
          mobile: "A4/modeles/A4_Berline_D.png",
          desktop: "A4/modeles/A4_Berline_D.png",
        },
      },
      {
        id: "A4_avant",
        name: "A4 Avant",
        position: 2,
        tracking: {
          derivat_name: "Avant",
        },
        volume: 1951,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: 418,
        aliases: ["carline.a4avant"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/a4-avant/finitions.html",
        description: "Le break familial de référence",
        images: {
          mobile: "A4/modeles/A4_Avant_D.png",
          desktop: "A4/modeles/A4_Avant_D.png",
        },
      },
      {
        id: "A4_allroad_quattro",
        name: "A4 allroad quattro",
        position: 3,
        tracking: {
          derivat_name: "allroad quattro",
        },
        volume: 99,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["carline.a4aq"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/a4-allroad-quattro.html",
        description: "Le break tout terrain",
        images: {
          mobile: "A4/modeles/A4_allroad_D.png",
          desktop: "A4/modeles/A4_allroad_D.png",
        },
      },
      {
        id: "S4_berline",
        name: "S4 Berline",
        position: 4,
        tracking: {
          derivat_name: "Berline",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["S4 TDI Berline", "carline.s4limo"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/s4-berline/moteurs.html",
        description: "La version S berline, plus dynamique",
        images: {
          mobile: "A4/modeles/S4_Berline_D.png",
          desktop: "A4/modeles/S4_Berline_D.png",
        },
      },
      {
        id: "S4_avant",
        name: "S4 Avant",
        position: 5,
        tracking: {
          derivat_name: "Avant",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["S4 TDI Avant", "carline.s4avant"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/s4-avant/moteurs.html",
        description: "La version S Avant, plus dynamique",
        images: {
          mobile: "A4/modeles/S4_Avant_D.png",
          desktop: "A4/modeles/S4_Avant_D.png",
        },
      },
      {
        id: "RS_4_avant",
        name: "RS 4 Avant",
        position: 6,
        tracking: {
          derivat_name: "RS 4 Avant",
        },
        volume: 21,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "18/11/2024",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["carline.rs4avant"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a4/rs-4-avant.html",
        description: "La version RS, façonnée par Audi Sport",
        images: {
          mobile: "A4/modeles/RS_4_Avant_D.png",
          desktop: "A4/modeles/RS_4_Avant_D.png",
        },
      },
    ],
  },
  {
    id: "Q4_e-tron",
    name: "Audi Q4 e-tron",
    position: 6,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=532",
    description:
      "La gamme Q4 est composée de 2 modèles de SUV Compacts 100% électriques adaptés à la ville offrant un grand espace intérieur.",
    backgrounds: {
      model_id: "Q4_e-tron",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q4e_tron.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q4_e_tron.webp",
    },
    volume: 2863,
    boost: 1.0,
    tag: ["SUV Compact", "Électrique"],
    models: [
      {
        id: "Q4_e-tron",
        name: "Q4 e-tron",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 1531,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 287,
        aliases: ["carline.q4etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q4-e-tron/audi-q4-e-tron/finitions.html",
        description: "Le SUV Compact 100% électrique",
        images: {
          mobile: "Q4 e-tron/modeles/Q4_e-tron_D.png",
          desktop: "Q4 e-tron/modeles/Q4_e-tron_D.png",
        },
      },
      {
        id: "Q4_sportback_e-tron",
        name: "Q4 Sportback e-tron",
        position: 2,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 1368,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 185,
        aliases: ["carline.q4sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q4-e-tron/audi-q4-sportback-e-tron/finitions.html",
        description: "Le SUV Coupé Compact 100% électrique",
        images: {
          mobile: "Q4 e-tron/modeles/Q4_Sportback_e-tron_D.png",
          desktop: "Q4 e-tron/modeles/Q4_Sportback_e-tron_D.png",
        },
      },
    ],
  },
  {
    id: "A5",
    name: "Audi A5",
    position: 7,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=5",
    description:
      "La gamme Audi A5 est composée de 8 modèles de 3 à 5 portes au design coupé pour une expérience de conduite intense.",
    backgrounds: {
      model_id: "A5_cabriolet",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a5.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a5.webp",
    },
    volume: 1348,
    boost: 1.0,
    tag: ["Berline", "Cabriolet", "Sportive"],
    models: [
      {
        id: "A5_coupé",
        name: "A5 Coupé",
        position: 1,
        tracking: {
          derivat_name: "Coupé",
        },
        volume: 83,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: 11,
        aliases: ["carline.a5coupe"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/a5-coupe/finitions.html",
        description: "Le coupé emblématique 3 portes",
        images: {
          mobile: "A5/modeles/A5_Coupe_D.png",
          desktop: "A5/modeles/A5_Coupe_D.png",
        },
      },
      {
        id: "A5_sportback",
        name: "A5 Sportback",
        position: 2,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 1007,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: 163,
        aliases: ["carline.a5sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/a5-sportback/finitions.html",
        description: "Le coupé emblématique 5 portes",
        images: {
          mobile: "A5/modeles/A5_Sportback_D.png",
          desktop: "A5/modeles/A5_Sportback_D.png",
        },
      },
      {
        id: "A5_cabriolet",
        name: "A5 Cabriolet",
        position: 3,
        tracking: {
          derivat_name: "Cabriolet",
        },
        volume: 153,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Cabriolet", 
        stock_level: 15,
        aliases: ["carline.a5cabrio"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/a5-cabriolet/finitions.html",
        description: "Le cabriolet élégant",
        images: {
          mobile: "A5/modeles/A5_Cabriolet_D.png",
          desktop: "A5/modeles/A5_Cabriolet_D.png",
        },
      },
      {
        id: "S5_coupé",
        name: "S5 Coupé",
        position: 4,
        tracking: {
          derivat_name: "S5 Coupé",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: -1,
        aliases: ["S5 TDI Coupé", "carline.s5coupe"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/s5-coupe/moteurs.html",
        description: "Le coupé 3 portes en version S, plus dynamique",
        images: {
          mobile: "A5/modeles/S5_Coupe_D.png",
          desktop: "A5/modeles/S5_Coupe_D.png",
        },
      },
      {
        id: "S5_sportback",
        name: "S5 Sportback",
        position: 5,
        tracking: {
          derivat_name: "S5 Sportback",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: -1,
        aliases: ["S5 TDI Sportback", "carline.s5sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/s5-sportback/moteurs.html",
        description: "Le coupé 5 portes en version S, plus dynamique",
        images: {
          mobile: "A5/modeles/S5_Sportback_D.png",
          desktop: "A5/modeles/S5_Sportback_D.png",
        },
      },
      {
        id: "S5_cabriolet",
        name: "S5 Cabriolet",
        position: 6,
        tracking: {
          derivat_name: "S5 Cabriolet",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Cabriolet", 
        stock_level: -1,
        aliases: [
          "S5 TFSI Cabriolet",
          "S5 TFSI  Cabriolet",
          "carline.s5cabrio",
        ],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/s5-cabriolet/moteurs.html",
        description: "Le cabriolet en version S, plus dynamique",
        images: {
          mobile: "A5/modeles/S5_Cabriolet_D.png",
          desktop: "A5/modeles/S5_Cabriolet_D.png",
        },
      },
      {
        id: "RS_5_coupé",
        name: "RS 5 Coupé",
        position: 7,
        tracking: {
          derivat_name: "RS 5 Coupé",
        },
        volume: 6,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: -1,
        aliases: ["carline.rs5coupe"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-coupe/packs.html",
        description: "La version RS 3 portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Coupe.png",
          desktop: "A5/modeles/RS_5_Coupe.png",
        },
      },
      {
        id: "RS_5_sportback",
        name: "RS 5 Sportback",
        position: 8,
        tracking: {
          derivat_name: "RS 5 Sportback",
        },
        volume: 13,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Coupé", 
        stock_level: -1,
        aliases: ["carline.rs5sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-sportback/packs.html",
        description: "La version RS 5 portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Sportback.png",
          desktop: "A5/modeles/RS_5_Sportback.png",
        },
      },
      {
        id: "NV_A5",
        name: "NV A5",
        position: 9,
        tracking: {
          derivat_name: "NV A5",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/11/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-sportback/packs.html",
        description: "La version NV A5 portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Sportback.png",
          desktop: "A5/modeles/RS_5_Sportback.png",
        },
      },
      {
        id: "NV_A5_avant",
        name: "NV A5 Avant",
        position: 10,
        tracking: {
          derivat_name: "NV A5 Avant",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/11/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-sportback/packs.html",
        description: "La version NV A5 Avant portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Sportback.png",
          desktop: "A5/modeles/RS_5_Sportback.png",
        },
      },
      {
        id: "NV_S5",
        name: "NV S5",
        position: 11,
        tracking: {
          derivat_name: "NV S5",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/11/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-sportback/packs.html",
        description: "La version NV_S5 portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Sportback.png",
          desktop: "A5/modeles/RS_5_Sportback.png",
        },
      },
      {
        id: "NV_S5_avant",
        name: "NV S5 Avant",
        position: 12,
        tracking: {
          derivat_name: "NV S5 Avant",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/11/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a5/rs-5-sportback/packs.html",
        description: "La version NV S5 Avant portes, façonnée par Audi Sport",
        images: {
          mobile: "A5/modeles/RS_5_Sportback.png",
          desktop: "A5/modeles/RS_5_Sportback.png",
        },
      },
    ],
  },
  {
    id: "Q5",
    name: "Audi Q5",
    position: 8,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=10",
    description:
      "La gamme Q5 est composée de 6 modèles de SUV iconiques Audi, incarnant confort, espace, design et dynamisme.",
    backgrounds: {
      model_id: "Q5_sportback",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q5.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q5.webp",
    },
    volume: 4239,
    boost: 1.0,
    tag: ["SUV", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "Q5",
        name: "Q5",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 669,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 33,
        aliases: ["Q5 SUV", "carline.q5"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5/finitions.html",
        description: "Le SUV iconique polyvalent",
        images: {
          mobile: "Q5/modeles/Q5_D.png",
          desktop: "Q5/modeles/Q5_D.png",
        },
      },
      {
        id: "Q5_tfsi_e",
        name: "Q5 TFSI e",
        position: 2,
        tracking: {
          derivat_name: "TFSI e",
        },
        volume: 1831,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 521,
        aliases: ["carline.q5etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-tfsi-e/finitions.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "Q5/modeles/Q5_TFSI_e_D.png",
          desktop: "Q5/modeles/Q5_TFSI_e_D.png",
        },
      },
      {
        id: "Q5_sportback",
        name: "Q5 Sportback",
        position: 3,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 1089,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 42,
        aliases: ["carline.q5sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-sportback/finitions.html",
        description: "Le SUV iconique en version coupée",
        images: {
          mobile: "Q5/modeles/Q5_Sportback_D.png",
          desktop: "Q5/modeles/Q5_Sportback_D.png",
        },
      },
      {
        id: "Q5_sportback_tfsi_e",
        name: "Q5 Sportback TFSI e",
        position: 4,
        tracking: {
          derivat_name: "Sportback TFSI e",
        },
        volume: 1734,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 615,
        aliases: ["carline.q5sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-sportback-tfsi-e/finitions.html",
        description: "La version coupée hybride rechargeable",
        images: {
          mobile: "Q5/modeles/Q5_Sportback_TFSI_e_D.png",
          desktop: "Q5/modeles/Q5_Sportback_TFSI_e_D.png",
        },
      },
      {
        id: "SQ5",
        name: "SQ5",
        position: 5,
        tracking: {
          derivat_name: "S",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["SQ5 TDI SUV", "carline.sq5"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/sq5-tdi/moteurs.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "Q5/modeles/SQ5_D.png",
          desktop: "Q5/modeles/SQ5_D.png",
        },
      },
      {
        id: "SQ5_sportback",
        name: "SQ5 Sportback",
        position: 6,
        tracking: {
          derivat_name: "S Sportback",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["SQ5 TDI Sportback", "carline.sq5sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/sq5-sportback/moteurs.html",
        description: "La version coupée S, plus dynamique",
        images: {
          mobile: "Q5/modeles/SQ5_Sportback_D.png",
          desktop: "Q5/modeles/SQ5_Sportback_D.png",
        },
      },
    ],
  },
  {
    id: "Q6_e-tron",
    name: "Audi Q6 e-tron",
    position: 8,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=10",
    description:
      "La gamme Q6 e-tron est composée de 4 modèles de SUV iconiques Audi, incarnant confort, espace, design et dynamisme.",
    backgrounds: {
      model_id: "Q6_e-tron",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q5.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q5.webp",
    },
    volume: 4239,
    boost: 1.0,
    tag: ["SUV", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "Q6_e-tron",
        name: "Q6 e-tron",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/03/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 212,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5/finitions.html",
        description: "Le SUV iconique polyvalent",
        images: {
          mobile: "Q5/modeles/Q5_D.png",
          desktop: "Q5/modeles/Q5_D.png",
        },
      },
      {
        id: "Q6_sportback_e-tron",
        name: "Q6 Sportback e-tron",
        position: 2,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/10/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-tfsi-e/finitions.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "Q5/modeles/Q5_TFSI_e_D.png",
          desktop: "Q5/modeles/Q5_TFSI_e_D.png",
        },
      },
      {
        id: "SQ6_e-tron",
        name: "SQ6 e-tron",
        position: 3,
        tracking: {
          derivat_name: "",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/03/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-sportback/finitions.html",
        description: "Le SUV iconique en version coupée",
        images: {
          mobile: "Q5/modeles/Q5_Sportback_D.png",
          desktop: "Q5/modeles/Q5_Sportback_D.png",
        },
      },
      {
        id: "SQ6_sportback_e-tron",
        name: "SQ6 Sportback e-tron",
        position: 4,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/11/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q5/q5-sportback-tfsi-e/finitions.html",
        description: "La version coupée hybride rechargeable",
        images: {
          mobile: "Q5/modeles/Q5_Sportback_TFSI_e_D.png",
          desktop: "Q5/modeles/Q5_Sportback_TFSI_e_D.png",
        },
      },
    ],
  },
  {
    id: "A6",
    name: "Audi A6",
    position: 9,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=6",
    description:
      "La gamme A6 est composée de 9 modèles de routières familiales adaptées à un grand nombre de passagers avec un volume de coffre généreux.",
    backgrounds: {
      model_id: "A6_avant",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a6.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a6.webp",
    },
    volume: 1083,
    boost: 1.0,
    tag: ["Berline", "Break", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "A6_berline",
        name: "A6 Berline",
        position: 1,
        tracking: {
          derivat_name: "Berline",
        },
        volume: 79,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 3,
        aliases: ["carline.a6limo"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-berline/finitions.html",
        description: "La berline routière",
        images: {
          mobile: "A6/modeles/A6_Berline_D.png",
          desktop: "A6/modeles/A6_Berline_D.png",
        },
      },
      {
        id: "A6_avant",
        name: "A6 Avant",
        position: 3,
        tracking: {
          derivat_name: "Avant",
        },
        volume: 453,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: 18,
        aliases: ["carline.a6avant"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-avant/finitions.html",
        description: "Le break familial de référence",
        images: {
          mobile: "A6/modeles/A6_Avant_D.png",
          desktop: "A6/modeles/A6_Avant_D.png",
        },
      },
      {
        id: "A6_allroad_quattro",
        name: "A6 allroad quattro",
        position: 5,
        tracking: {
          derivat_name: "allroad quattro",
        },
        volume: 64,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["carline.a6aq"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-allroad-quattro/finitions.html",
        description: "Le break tout terrain haut de gamme",
        images: {
          mobile: "A6/modeles/A6_allroad_D.png",
          desktop: "A6/modeles/A6_allroad_D.png",
        },
      },
      {
        id: "A6_berline_tfsi_e",
        name: "A6 Berline TFSI e",
        position: 2,
        tracking: {
          derivat_name: "Berline TFSI e",
        },
        volume: 99,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 39,
        aliases: [
          "A6 TFSI e quattro Berline ",
          "A6  TFSI e quattro Berline",
          "carline.a6limoetron",
        ],
        cta_label: "Configurer",
        url: "https://www.audi.fr/content/fr/web/fr/gamme/a6/a6-berline-tfsi-e/finitions.html",
        description: "La berline en version hybride rechargeable",
        images: {
          mobile: "A6/modeles/A6_Berline_TFSI_e_D.png",
          desktop: "A6/modeles/A6_Berline_TFSI_e_D.png",
        },
      },
      {
        id: "A6_avant_tfsi_e",
        name: "A6 Avant TFSI e",
        position: 4,
        tracking: {
          derivat_name: "Avant TFSI e",
        },
        volume: 604,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: 213,
        aliases: ["A6 TFSI e quattro Avant"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-avant-tfsi-e/finitions.html",
        description: "Le break en version hybride rechargeable",
        images: {
          mobile: "A6/modeles/A6_Avant_TFSI_e_D.png",
          desktop: "A6/modeles/A6_Avant_TFSI_e_D.png",
        },
      },
      {
        id: "S6_berline",
        name: "S6 Berline",
        position: 6,
        tracking: {
          derivat_name: "S6 Berline",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["S6 TDI Berline", "carline.s6limo"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/s6-berline/moteurs.html",
        description: "La version S berline, plus dynamique",
        images: {
          mobile: "A6/modeles/S6_Berline_D.png",
          desktop: "A6/modeles/S6_Berline_D.png",
        },
      },
      {
        id: "S6_avant",
        name: "S6 Avant",
        position: 7,
        tracking: {
          derivat_name: "S6 Avant",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["S6 TDI Avant", "carline.s6avant"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/s6-avant/moteurs.html",
        description: "La version S break, plus dynamique",
        images: {
          mobile: "A6/modeles/S6_Avant_D.png",
          desktop: "A6/modeles/S6_Avant_D.png",
        },
      },
      {
        id: "RS_6_avant",
        name: "RS 6 Avant",
        position: 8,
        tracking: {
          derivat_name: "RS 6 Avant",
        },
        volume: 174,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: ["carline.rs6avant"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/rs-6-avant.html",
        description: "La version RS break, façonnée par Audi Sport",
        images: {
          mobile: "A6/modeles/RS_6_Avant_D.png",
          desktop: "A6/modeles/RS_6_Avant_D.png",
        },
      },
      {
        id: "RS_6_avant_performance",
        name: "RS 6 Avant performance",
        position: 9,
        tracking: {
          derivat_name: "RS 6 Avant performance",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/rs-6-avant-performance/packs.html",
        description: "La version RS break performance, la plus radicale",
        images: {
          mobile: "A6/modeles/RS_6_Avant_performance_D.png",
          desktop: "A6/modeles/RS_6_Avant_performance_D.png",
        },
      },
    ],
  },
  {
    id: "A6_e-tron",
    name: "Audi A6 e-tron",
    position: 9,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=6",
    description:
      "La gamme A6 e-tron est composée de 2 modèles de routières familiales adaptées à un grand nombre de passagers avec un volume de coffre généreux.",
    backgrounds: {
      model_id: "A6_sportback_e-tron",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a6.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a6.webp",
    },
    volume: 1083,
    boost: 1.0,
    tag: ["Berline", "Break", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "A6_sportback_e-tron",
        name: "A6 Sportback e-tron",
        position: 1,
        tracking: {
          derivat_name: "A6 Sportback e-tron",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/08/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-berline/finitions.html",
        description: "A6 Sportback e-tron La berline routière",
        images: {
          mobile: "A6/modeles/A6_Berline_D.png",
          desktop: "A6/modeles/A6_Berline_D.png",
        },
      },
      {
        id: "A6_avant_e-tron",
        name: "A6 Avant e-tron",
        position: 2,
        tracking: {
          derivat_name: "A6 Avant e-tron",
        },
        volume: 100000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "01/08/2024",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Break", 
        stock_level: -1,
        aliases: [],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a6/a6-avant/finitions.html",
        description: "A6 Avant e-tron Le break familial de référence",
        images: {
          mobile: "A6/modeles/A6_Avant_D.png",
          desktop: "A6/modeles/A6_Avant_D.png",
        },
      },
    ],
  },
  {
    id: "A7",
    name: "Audi A7",
    position: 10,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=7",
    description:
      "La gamme A7 est composée  de 4 modèles de grandes berlines au design coupé.",
    backgrounds: {
      model_id: "S7_sportback",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a7.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a7.webp",
    },
    volume: 95,
    boost: 1.0,
    tag: ["Berline", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "A7_sportback",
        name: "A7 Sportback",
        position: 1,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 46,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 1,
        aliases: ["carline.a7sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a7/a7-sportback/finitions.html",
        description: "La berline coupée au design d’exception",
        images: {
          mobile: "A7/modeles/A7_Sportback_D.png",
          desktop: "A7/modeles/A7_Sportback_D.png",
        },
      },
      {
        id: "A7_sportback_tfsi_e",
        name: "A7 Sportback TFSI e",
        position: 2,
        tracking: {
          derivat_name: "Sportback TFSI e",
        },
        volume: 80,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 19,
        aliases: ["carline.a7sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a7/a7-sportback-tfsi-e/finitions.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "A7/modeles/A7_Sportback_TFSI_e_D.png",
          desktop: "A7/modeles/A7_Sportback_TFSI_e_D.png",
        },
      },
      {
        id: "S7_sportback",
        name: "S7 Sportback",
        position: 3,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["S7 TDI Sportback", "carline.s7sb"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a7/s7-sportback/moteurs.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "A7/modeles/S7_Sportback_D.png",
          desktop: "A7/modeles/S7_Sportback_D.png",
        },
      },
      {
        id: "RS_7_sportback",
        name: "RS 7 Sportback",
        position: 4,
        tracking: {
          derivat_name: "RS 7 Sportback",
        },
        volume: 17,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["carline.rs7sb"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/a7/rs-7-sportback.html",
        description: "La version RS, façonnée par Audi Sport",
        images: {
          mobile: "A7/modeles/RS_7_Sportback_D.png",
          desktop: "A7/modeles/RS_7_Sportback_D.png",
        },
      },
      {
        id: "RS_7_sportback_performance",
        name: "RS 7 Sportback Performance",
        position: 4,
        tracking: {
          derivat_name: "RS 7 Sportback Performance",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["RS 7 Sportback performance"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a7/rs-7-sportback-performance/finitions.html",
        description: "La version RS performance, la plus radicale",
        images: {
          mobile: "A7/modeles/RS_7_Sportback_performance_D.png",
          desktop: "A7/modeles/RS_7_Sportback_performance_D.png",
        },
      },
    ],
  },
  {
    id: "Q7",
    name: "Audi Q7",
    position: 11,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=11",
    description:
      "La gamme Q7 est composée de 3 modèles de grands SUV familiaux luxueux allant jusqu'à 7 places.",
    backgrounds: {
      model_id: "SQ7",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q7.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q7.webp",
    },
    volume: 152,
    boost: 1.0,
    tag: ["Grand SUV", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "Q7",
        name: "Q7",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 36,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 1,
        aliases: ["carline.q7"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q7/q7.html",
        description: "Le grand SUV haut de gamme familial",
        images: {
          mobile: "Q7/modeles/Q7_D.png",
          desktop: "Q7/modeles/Q7_D.png",
        },
      },
      {
        id: "Q7_tfsi_e",
        name: "Q7 TFSI e",
        position: 2,
        tracking: {
          derivat_name: "TFSI e",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 74,
        aliases: ["carline.q7etron"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q7/q7-tfsi-e.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "Q7/modeles/Q7_TFSI_e_D.png",
          desktop: "Q7/modeles/Q7_TFSI_e_D.png",
        },
      },
      {
        id: "SQ7",
        name: "SQ7",
        position: 3,
        tracking: {
          derivat_name: "S",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["SQ7 TFSI", "carline.sq7"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q7/sq7.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "Q7/modeles/SQ7_D.png",
          desktop: "Q7/modeles/SQ7_D.png",
        },
      },
    ],
  },
  {
    id: "A8",
    name: "Audi A8",
    position: 12,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=8",
    description:
      "La gamme A8 est composée de 4 modèles de berlines équipées de toutes les nouvelles technologies avant-gardistes de la marque.",
    backgrounds: {
      model_id: "A8",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_a8.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_a8.webp",
    },
    volume: 64,
    boost: 1.0,
    tag: ["Grande berline", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "A8",
        name: "A8",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 14,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 0,
        aliases: ["A8 Facelift Berline", "carline.a8"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a8/a8/finitions.html",
        description: "La berline de luxe",
        images: {
          mobile: "A8/modeles/A8_D.png",
          desktop: "A8/modeles/A8_D.png",
        },
      },
      {
        id: "S8",
        name: "S8",
        position: 4,
        tracking: {
          derivat_name: "S8",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 9,
        aliases: ["S8 Facelift", "carline.s8"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a8/s8/moteurs.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "A8/modeles/S8_D.png",
          desktop: "A8/modeles/S8_D.png",
        },
      },
      {
        id: "A8_tfsi_e",
        name: "A8 TFSI e",
        position: 2,
        tracking: {
          derivat_name: "TFSI e",
        },
        volume: 73,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 9,
        aliases: ["A8 Berline TFSI e quattro", "carline.a8etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/a8/a8-tfsi-e/finitions.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "A8/modeles/A8_TFSI_e_D.png",
          desktop: "A8/modeles/A8_TFSI_e_D.png",
        },
      },
      {
        id: "A8_l_tfsi_e",
        name: "A8 L TFSI e",
        position: 3,
        tracking: {
          derivat_name: "L",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["A8 Limousine TFSI e quattro", "carline.a8letron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr//fr/web/fr/gamme/a8/a8-l-tfsi-e/finitions.html",
        description: "La limousine de luxe",
        images: {
          mobile: "A8/modeles/A8_L_TFSI_e_D.png",
          desktop: "A8/modeles/A8_L_TFSI_e_D.png",
        },
      },
    ],
  },
  {
    id: "Q8",
    name: "Audi Q8",
    position: 13,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=529",
    description:
      "La gamme Q8 est composée de 4 modèles de grands SUV Coupés luxueux au design racé.",
    backgrounds: {
      model_id: "SQ8",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_sq8.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_sq8.webp",
    },
    volume: 438,
    boost: 1.0,
    tag: ["Grand SUV", "Sportive", "Hybride rechargeable"],
    models: [
      {
        id: "Q8",
        name: "Q8",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 16,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 61,
        aliases: ["carline.q8"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8/q8.html",
        description: "Le grand SUV Coupé haut de gamme",
        images: {
          mobile: "Q8/modeles/Q8_D.png",
          desktop: "Q8/modeles/Q8_D.png",
        },
      },
      {
        id: "Q8_tfsi_e",
        name: "Q8 TFSI e",
        position: 2,
        tracking: {
          derivat_name: "TFSI e",
        },
        volume: 893,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: 333,
        aliases: ["carline.q8tfsie"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8/q8-tfsi-e.html",
        description: "La version hybride rechargeable",
        images: {
          mobile: "Q8/modeles/Q8_TFSI_e_D.png",
          desktop: "Q8/modeles/Q8_TFSI_e_D.png",
        },
      },
      {
        id: "SQ8",
        name: "Nouvelle SQ8",
        position: 3,
        tracking: {
          derivat_name: "S",
        },
        volume: 90000,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["SQ8 TFSI", "carline.sq8"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8/sq8/moteurs.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "Q8/modeles/SQ8.png",
          desktop: "Q8/modeles/SQ8.png",
        },
      },
      {
        id: "RS_Q8",
        name: "RS Q8",
        position: 4,
        tracking: {
          derivat_name: "RS",
        },
        volume: 30,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.rsq8"],
        cta_label: "En savoir plus",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8/rs-q8.html",
        description: "La version RS, façonnée par Audi Sport",
        images: {
          mobile: "Q8/modeles/RS_Q8_D.png",
          desktop: "Q8/modeles/RS_Q8_D.png",
        },
      },
    ],
  },
  {
    id: "Q8_e-tron",
    name: "Audi Q8 e-tron",
    position: 14,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=534",
    description:
      "La gamme Q8 e-tron est composée de 4 modèles de grands SUV 100% électriques pionniers du nouveau design e-tron Audi.",
    backgrounds: {
      model_id: "Q8_sportback_e-tron",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_q8e_tron.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_q8_e_tron.webp",
    },
    volume: 600,
    boost: 1.0,
    tag: ["Grand SUV", "Sportive", "Électrique"],
    models: [
      {
        id: "Q8_e-tron",
        name: "Q8 e-tron",
        position: 1,
        tracking: {
          derivat_name: "",
        },
        volume: 320,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.q8etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8-e-tron/audi-q8-e-tron/finitions.html",
        description: "Le grand SUV 100% électrique",
        images: {
          mobile: "Q8 e-tron/modeles/Q8_e-tron_D.png",
          desktop: "Q8 e-tron/modeles/Q8_e-tron_D.png",
        },
      },
      {
        id: "Q8_sportback_e-tron",
        name: "Q8 Sportback e-tron",
        position: 2,
        tracking: {
          derivat_name: "Sportback",
        },
        volume: 675,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.q8sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8-e-tron/audi-q8-sportback-e-tron/finitions.html",
        description: "Le grand SUV Coupé 100% électrique",
        images: {
          mobile: "Q8 e-tron/modeles/Q8_Sportback_e-tron_D.png",
          desktop: "Q8 e-tron/modeles/Q8_Sportback_e-tron_D.png",
        },
      },
      {
        id: "SQ8_e-tron",
        name: "SQ8 e-tron",
        position: 3,
        tracking: {
          derivat_name: "S",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.sq8etron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8-e-tron/audi-sq8-e-tron/moteurs.html",
        description: "La version S, plus dynamique",
        images: {
          mobile: "Q8 e-tron/modeles/SQ8_e-tron_D.png",
          desktop: "Q8 e-tron/modeles/SQ8_e-tron_D.png",
        },
      },
      {
        id: "SQ8_sportback_e-tron",
        name: "SQ8 Sportback e-tron",
        position: 4,
        tracking: {
          derivat_name: "S Sportback",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "SUV", 
        stock_level: -1,
        aliases: ["carline.sq8sbetron"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/q8-e-tron/audi-sq8-sportback-e-tron/moteurs.html",
        description: "La version coupée S, plus dynamique",
        images: {
          mobile: "Q8 e-tron/modeles/SQ8_Sportback_e-tron_D.png",
          desktop: "Q8 e-tron/modeles/SQ8_Sportback_e-tron_D.png",
        },
      },
    ],
  },
  {
    id: "e-tron_GT",
    name: "Audi e-tron GT",
    position: 15,
    url: "https://france.my.audi.com/information/?formId=4033&type=qamc&range=531",
    description:
      "La gamme e-tron GT est composée de 2 modèles de berlines coupées 100% électriques ambassadrices de la performance électrique par Audi.",
    backgrounds: {
      model_id: "e-tron_gt_quattro",
      mobile: "Visuels_moduleQAMC/Gammes/780x585_e_trongt.webp",
      desktop: "Visuels_moduleQAMC/Gammes/1920x600_e_trongt.webp",
    },
    volume: 44,
    boost: 1.0,
    tag: ["Berline", "Sportive", "Électrique"],
    models: [
      {
        id: "e-tron_gt_quattro",
        name: "e-tron GT quattro",
        position: 1,
        tracking: {
          derivat_name: "quattro",
        },
        volume: 356,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: 48,
        aliases: ["carline.etrongt"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/e-tron-gt/audi-e-tron-gt-quattro/finitions.html",
        description: "La berline coupée 100% électrique",
        images: {
          mobile: "e-tron GT/modeles/e-tron_GT_quattro_D.png",
          desktop: "e-tron GT/modeles/e-tron_GT_quattro_D.png",
        },
      },
      {
        id: "RS_e-tron_gt",
        name: "RS e-tron GT",
        position: 2,
        tracking: {
          derivat_name: "RS GT",
        },
        volume: 0,
        incentive_text:
          "Aliquam placerat ultrices odio vehicula convallis. Duis porta rutrum consequat. Nullam in quam arcu. Cras laoreet et quam hendrerit blandit. In malesuada purus a placerat elementum. Suspendisse interdum diam vel risus varius auctor. Aliquam bibendum bibendum odio, at rhoncus tellus ultricies at. Donec vel maximus sapien, quis suscipit elit.",
        start_date: "",
        end_date: "",
        number_places: 5,
        number_doors: 5,
        number_luggages: 2,
        category: "Berline", 
        stock_level: -1,
        aliases: ["carline.rsetrongt"],
        cta_label: "Configurer",
        url: "https://www.audi.fr/fr/web/fr/gamme/e-tron-gt/audi-rs-e-tron-gt/finitions.html",
        description: "La version RS, façonnée par Audi Sport",
        images: {
          mobile: "e-tron GT/modeles/RS_e-tron_GT_D.png",
          desktop: "e-tron GT/modeles/RS_e-tron_GT_D.png",
        },
      },
    ],
  },
];
